### PR TITLE
Update README and add server

### PR DESCRIPTION
**Pull request by the7thNightmare**
I change the gradle command matching the heroku command, I also add my server (still don't know if it work tho).

Also, there's a various environment variable in [server launcher file](https://github.com/retrowars/retrowars/blob/master/server/src/com/serwylo/retrowars/server/ServerLauncher.kt), is it the variable for the server or not? Cause I don't know how to test it tho.

### CODE REVIEW

**Comment by pserwylo** [comment]
Hi, thanks so much for the offer of this server! And thanks also for the updated README.

## Regarding the server configuration in this PR

The main issue with the current server is the usage of `https`. Right now the game only supports `http` servers. Here is the output when contacting your server on port 80, showing the `HTTP 301` redirect to the `https` endpoint which we'd need to remove:

```
$ curl http://rwr.nekoweb.my.id/info --verbose

* Connected to rwr.nekoweb.my.id (203.194.112.126) port 80 (#0)
> GET /info HTTP/1.1
> Host: rwr.nekoweb.my.id
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://rwr.nekoweb.my.id/info
<
<html>
<head><title>301 Moved Permanently</title></head>
</html>
```

```
$ curl https://rwr.nekoweb.my.id/info --verbose

* Connected to rwr.nekoweb.my.id (203.194.112.126) port 443 (#0)
* SSL certificate problem: self signed certificate in certificate chain
* 
curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. To learn more about this situation and how to fix it, please visit the web page mentioned above.
```

```
$ curl https://rwr.nekoweb.my.id/info --insecure
          
{"versionCode":52,"versionName":"0.31.1","minSupportedClientVersionCode":49,"minSupportedClientVersionName":"0.29.0","type":"publicRandomRooms","maxPlayersPerRoom":4,"maxRooms":20,"currentRoomCount":0,"currentPlayerCount":0,"lastGameTimestamp":-1,"lastPlayerTimestamp":-1}% 
```

## Regarding testing a server

**Short term solution**

Once we drop the HTTPS redirect shown above, I'd be happy to just merge this PR so we can test using the regular game. Worst case - we have three working servers and one broken one while we iron out the issues.

**Long term solution**

The game should have a "Join private server" option which allows people to enter their own server names (e.g. for playing privately with their friends). This would also prove helpful for testing new servers too.

If you don't feel comfortable with the above short term solution, I'd be happy to pursue adding this feature to the game, but beware it may take a week or two given my availability.

## Regarding the arguments/env vars

Feel free to configure as you see fit, or leave as defaults. You can either use the env vars or the command line arguments. I'll add documentation to them in the README here after we mereg this, but for a short summary:
* `PORT`: Changes the port the server listens on. Would of course require changing the port in the `docs/.well-known/com.serwylo.retrowars-servers.json` file too if required (though more likely, it will be behind a reverse proxy and this port is the port of the Java app which is not directly exposed to the net).
* `MAX_ROOMS`: In a theoretical world where lots of people actually played this game (we are but a small game with only a few players - but we can dream!) this would help prevent your server accepting unlimited connections, and would politely reject connection attempts when the max rooms have been reached.
* `ROOM_SIZE`: Number of players that can live in one room before the next room is automatically opened. Too many can cause (sometimes fun) chaos, but you may wish, e.g. to support just a Player vs Player server where rooms can only support 2 players.
* `FINAL_SCORE_DURATION`: Number of milliseconds to show the end game screen before opening the lobby for the next round.
* `INACTIVE_PLAYER_TIMEOUT`: If somebody drops out of network connection and can't reach the server, we don't want them permanently sitting in the game lobby until the server is restarted. This kicks players after not receiving a ping for this long. Clients will ping every 30 seconds under normal circumstances.
* `BETA_GAMES`: Most beta games don't actually support multiplayer (it is typically the last feature I implement when adding a game), so I'd leave this as off.

**Comment by the7thNightmare** [comment]
Thanks, I already fix the redirection. With the output as follow:
```
curl http://rwr.nekoweb.my.id/info --verbose

*   Trying 2001:df0:27b::31:80...
* Connected to rwr.nekoweb.my.id (2001:df0:27b::31) port 80 (#0)
> GET /info HTTP/1.1
> Host: rwr.nekoweb.my.id
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/json; charset=UTF-8
< Content-Length: 272
< Connection: keep-alive
< 
* Connection #0 to host rwr.nekoweb.my.id left intact
{"versionCode":52,"versionName":"0.31.1","minSupportedClientVersionCode":49,"minSupportedClientVersionName":"0.29.0","type":"publicRandomRooms","maxPlayersPerRoom":4,"maxRooms":20,"currentRoomCount":0,"currentPlayerCount":0,"lastGameTimestamp":-1,"lastPlayerTimestamp":-1}
```

**Comment by pserwylo** [comment]
Thanks. Did a quick test on my local PC where I compiled two copies with this new server list, and it seems to work well:

image

I'll go ahead and merge. You're contribution is awesome, and I'm very thankful. But if you ever feel like it is too much work to keep the server up, feel free to post a new PR here to remove it, or just ask here and I can do that for you too.

**Comment by the7thNightmare** [comment]
Hello, it seems that my server is broken right now, so can my server be removed?

Thank you.

**Pull request merged**
