### PR TITLE
Add 2 rwars-*.ggorg.xyz servers (with HTTPS!)

### PR DESCRIPTION
**Pull request by GGORG0**

### CODE REVIEW

**Comment by pserwylo** [comment]
Thanks for following this up. Testing this PR made me realise that I should update the `/info` endpoint for the server software so that it includes the list of supported games. 

It is annoying to test, but when I hardcode the `fetchPublicServerList()` function to return your to servers, I see that the `tetris` one works well, but the `rwars-sn-br-si.ggorg.xyz` server also only returns `tetris`. Not sure if this is an issue with the server configuration, or a bug in the code.

In the meantime, I'll go and update the code to support this updated endpoint. In the future I'll also update the client so that it shows the games supported by each server.

**Comment by pserwylo** [comment]
I've updated the server, and tagged and released v0.32.2 which makes the server report the supported games via the `/info` endpoint. Hopefully that will help with testing this. Cheers.

**Comment by pserwylo** [comment]
image

**Comment by GGORG0** [comment]
Ok, I'll update both servers now and see if I messed something up too

**Comment by GGORG0** [comment]
So the other server was meant to provide only snake, breakout and space invaders, but I forgot to recreate the containers after updating the docker compose file with them - so that problem was on my end!

It was a bit of a hassle to force docker to rebuild the container, because it thought that it can just use the cache (cloning git repositories inside a dockerfile is bad, because docker has no idea whether it got updated or not - I recommend just moving the dockerfile to the main retrowars repo - it will make updating the image way easier!). 

But I managed to fix all of that and now everything works as it should.

**Comment by pserwylo** [comment]
Awesome, thanks for the pointers. Normally I'd encourage what you've done, by putting your servers at the bottom of the list, but can I ask in this PR that you put them below the `retrowars-latest.serwylo.com` entry? And while you are at it, move `retrowars1.serwylo.com` to the bottom?

The reason is that most additional servers operate as a backup in case my servers go down. Other than that they don't offer anything else (except perhaps a better ping, but we are not playing FPS's here). This is no fault of the wonderful server operators, but rather there was never any option to provide new features.

Now that your servers offer the player something different that they may be interested in, I'd like to show that off.

Although it is not obvious now, I'm putting together this UI which I will release soon that will help explain that your servers support specific games. Once released, you will be free to rename your hostnames to whatever you want, because the host name will no longer be the main way in which players learn what your server supports:

image

**Comment by GGORG0** [comment]
There you go!

Even if the UI is out, I think I will keep my domains as is, because:
1. someone might have an older version of the game without that feature
2. it will be easier to know what is what when just looking at the domain outside of the game - and that's also the way I have all my naming set up in my docker-compose homelab!

**Comment by pserwylo** [comment]
Thank you so much for your inout and the kind offer of these servers. Obviously there is no obligation to keep them forever, so feel free to file a PR to remove them if it becomes burdensome.

**Pull request merged**
