### PR TITLE
New server for retrowar

### PR DESCRIPTION
**Pull request by azlux**
Hi,
I propose you a new server for your games.

Can you check if everything's good ?

Best regards
Azlux

### CODE REVIEW

**Comment by pserwylo** [comment]
This is great, thank you so much for the contribution!

Would you like to update the PR to put this second in the list, like so:

* retrowars-latest.serwylo.com
* yours
* retrowars1.serwylo.com
* retrowars2.serwylo.com

The reason being that `retrowars1.serwylo.com` is designed to always be for people who have not yet upgraded far enough (in this case, those who don't have space invaders in their app yet), and `retrowars2.serwylo.com` is a Heroku server with the latest version, but is just a backup because they are more trustworthy than my own little EC2 instance hosting retrowars-latest.serwylo.com (in case mine goes down - this wont - but it will take 20 seconds to boot if it hasn't been hit for half an hour). I think I'll rename these to `retrowars-older.serwylo.com` + `retrowars-backup.serwylo.com` to make this ever-so-slightly-more-clear.

If we update to the order above, then the intent is that most people hit `retrowars-latest` as a semi "official" server run by me, but yours will be a better alternative than the other two for *most* cases.

Tested and works well (by building retrowars locally and pointing it to https://cdn.jsdelivr.net/gh/azlux/retrowars-servers@patch-1/docs/.well-known/com.serwylo.retrowars-servers.json which is a mirror to the JSON file in this PR (had to use that instead of the "raw" URL from GitHub because that returns `Content-Type: text/plain` instead of `text/json` which seems to be required by the game).

This also makes me think that I should make the game look in some predefined locations for a URL that can be overridden (e.g. `/storage/sdcard/apps/com.serwylo.retrowars/server-list-url.txt`, and if it exists, use that instead. Otherwise, it is tricky for contributors to see if their server works as expected.

**Comment by pserwylo** [comment]
Thanks again for this, all merged.

Don't be surprised if it is relatively quiet. On a good day, I see about 35 people join the main retrowars server over the course of a day. This has slowly increased over time, and I plan on continuing development and encouraging people to download and play. Hopefully the numbers pick up as I keep releasing new versions that keep getting onto the "What's New" page of F-Droid regularly, but there is no expectation that this will become the next multi-million-player online game :smile:.

A sneaky little secret - all the game computations are done locally, the server just forwards connection events and events about change of scores, etc. In the future, I'd love to have the server as the authority on what happens during a game (that would allow things like watching live games as they are in play, and also preventing cheating. However as a little hobby game right now, I'm happy to just put trust in the clients for now. This is why the servers don't need a lot of resources hopefully.

In the future, please do not feel bad reaching out and removing your server from the list if it becomes onerous. Hopefully it runs smoothly and quietly though - let me know if there are any issues/crashes which you think need addressing.

**Comment by azlux** [comment]
I will check the load graphs, but I'm not worry about it.
As a opensource lover, when I see a good project like this one, I'm happy to help.
The only weird thing I currently see is to have debug log activated by default.

**Comment by pserwylo** [comment]
Good call, I'll update the readme explaining that this can be configured by `/etc/retrowars/logback.xml`. Here is the one from my server:

```
<included>
<property name="LOG_FILE" value="server" />
<property name="LOG_DIR" value="/var/log/retrowars" />
<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>${LOG_DIR}/${LOG_FILE}.log</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
        <!-- daily rollover -->
        <fileNamePattern>${LOG_DIR}/${LOG_FILE}.%d{yyyy-MM-dd}.gz</fileNamePattern>

        <!-- keep 30 days' worth of history capped at 1GB total size -->
        <maxHistory>30</maxHistory>
        <totalSizeCap>1GB</totalSizeCap>
    </rollingPolicy>
    <encoder>
        <pattern>%date [%thread] %-5level %logger{36} - %msg%n</pattern>
    </encoder>
</appender> 
<root level="debug">
    <appender-ref ref="FILE" />
</root>
</included>
```

The key thing being you can change `<root level="debug">` to [either `error`, `warn`, or `info` instead](https://logback.qos.ch/apidocs/ch/qos/logback/classic/Level.html).

I'll probably also change the default to be `info` instead in the source code. The history of leaving it as `debug` was because I had no idea what to inspect in terms of number of players, bugs, and importantly the balancing of games - still don't think it is perfectly balanced, but one day I'll look at the raw data of which games win most commonly and try to rebalance the scoring accordingly).

**Comment by pserwylo** [comment]
Hey @azlux - as an early adopter, I've accidentally caused a bug in your server while I was playing with someone else on the train today. Intermittent connection, ended up getting it stuck thinking both I and another player are in a room there. 

Easiest fix for now is probably just to restart it periodically, but I have a proper fix I'm going to go implement now and will ping here when done (may take a couple of days to find the time). That is - the server already receives a ping from the client every 20s or so. This is to ensure that websocket connections do not time out on Heroku instances. I am going to make it so that if the server doesn't receive a ping from a player in, say 40s (double the expected time) then it will kick them from the room.

**Comment by pserwylo** [comment]
I should clarify, the bug is not in your server, it is most certainly in my networking code!

**Comment by azlux** [comment]
No prob, I've restart the container.
Most game wait 3-5 minutes idle gamer before kicking the user.
(You can use my direct email on my profile to reach me is needed)

**Pull request merged**
